### ISSUE TITLE
Refresh community policies

### ISSUE THREAD

**Issue by ulrikeyang** [xsdk-project/xsdk-community-policies#9]
For our milestone on documenting the community policies we should take a look at them and see where editorial changes or more are needed.

Here are a few issues I noticed:

- **M5** ends with the following sentences:
The IDEAS project will not provide a go-between for users of xSDK packages and xSDK member packages. The xSDK strategy is to make sure that the xSDK functionality fits naturally into existing library support models.
The first sentence does no longer make sense and should be deleted.
I am not really sure how the last sentence fits here. We should discuss this.

- ***M13** contains the following sentence:
In addition, the libraries and header files should not have the version number embedded in them ...
It is not completely clear what is meant by `them'. I suggest to replace `them' with `the names'.

**Comment by jedbrown** [comment]
Perhaps: "library and header file names should not have ..."

**Comment by balay** [comment]
Wrt: **M8** I would like to see something like:

```
For C/C++/Fortran libraries - with public include files - recommend providing version
in a format one can use and compare via CPP. for ex:
```
```
#if H5_VERSION_GE(1,10,3)
/* code */ 
#else
/* code */
#endif
```

**Comment by BarrySmith** [comment]
8    

Determine index size for packages that build only for one index size (default is 32). Packages that handle all precisions automatically are free to ignore this option.

precisions -> index sizes

**Comment by BarrySmith** [comment]
13
After an install the package should provide a machine-readable output to show provenance, that is, what compilers were used and what libraries were linked with, as well as other build configuration information if this information was also stored in the install directory somewhere, so that users with problems can send the information directly to developers.

Suggest dropping "if this information was also stored in the install directory somewhere,"  The information should be provided in the install directory so there should be no question of "if this information was also stored"

**Comment by BarrySmith** [comment]
M3
The package should use configure tests or version tests to detect MPI 2 ...

Suggest dropping the requirement to test for MPI 2 features. xSDK should now just assume complete MPI 2 implementations are always available. PETSc has been verifying this for several years and it doesn't seem to be a problem, everyone has access to MPI 2 it seems.

**Comment by ulrikeyang** [comment]
This has been reviewed and all pull requests except for new proposed policy R8 have been approved.
